{{- if dig "enabled" true (.Values.mysql | default dict) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ansibleforms.mysql.fullname" . }}-my-cnf
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ansibleforms.mysql.labels" . | nindent 4 }}
  {{- with (include "ansibleforms.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
data:
  my.cnf: |
    [mysqld]
{{- end }}
